[Interface]
PrivateKey = uMW+UYQx6SvQZykAoJdY7H/YaVyU+3J+/LJvBrAwBkI=
Address = 10.77.0.10/32
MTU = 1420
DNS = 1.1.1.1

[Peer]
PublicKey = kVPBj62PpMaG0Zx50r+H+f2H+F+7sKbXYGS2EkMsdBo=
AllowedIPs = 0.0.0.0/0
Endpoint = 217.26.26.9:443
PersistentKeepalive = 21